## Equal Weights Strategy

In [5]:
import pandas as pd
import numpy as np
import yfinance as yf
import math

## Load the Stocks List

In [43]:
tickers = pd.read_csv('top_50_stocks.csv')
tickers.head()

  Ticker           Company Name
0   AAPL             Apple Inc.
1   MSFT  Microsoft Corporation
2   AMZN        Amazon.com Inc.
3  GOOGL          Alphabet Inc.
4   TSLA             Tesla Inc.

In [44]:
def fetch_market_cap(ticker_list):
    data = yf.download(ticker_list, period = '1d', group_by = 'ticker', auto_adjust = False)
    
    stocks_data = []
    for ticker in ticker_list:
        latest_price = data[ticker]['Close'].iloc[-1]
        market_cap = yf.Ticker(ticker).info.get('marketCap', 'N/A')
        stocks_data.append({
            "Ticker" : ticker,
            "Market Cap" : market_cap,
            "Latest Price" : latest_price,
        })
        
    stocks_df = pd.DataFrame(stocks_data)
        
    return stocks_df

tickers_list = tickers["Ticker"].values.tolist()
df = fetch_market_cap(tickers_list)
df.head()

[*********************100%***********************]  50 of 50 completed

  Ticker     Market Cap  Latest Price
0   AAPL  3676245065728    250.119995
1   MSFT  2939877064704    395.549988
2   AMZN  2229321072640    207.669998
3  GOOGL  3656681259008    302.279999
4   TSLA  1467951349760    391.200012

In [45]:
df = df.sort_values(by = "Market Cap", ascending = False)
df

   Ticker     Market Cap  Latest Price
5    NVDA  4380976218112    180.250000
0    AAPL  3676245065728    250.119995
3   GOOGL  3656681259008    302.279999
1    MSFT  2939877064704    395.549988
2    AMZN  2229321072640    207.669998
23    TSM  1754646446080    338.309998
4    TSLA  1467951349760    391.200012
9     WMT  1008725131264    126.519997
6     JPM   764446900224    283.440002
30    XOM   650515120128    156.119995
8       V   592178118656    307.140015
7     JNJ   582038847488    241.520004
38   ORCL   445800251392    155.110001
11     MA   444425043968    497.989990
18   NFLX   404294467584     95.309998
31    CVX   393512779776    196.820007
10     PG   352594100224    150.649994
14    BAC   341172617216     46.720001
13     HD   337508270080    339.029999
26     KO   332686426112     77.339996
49    CAT   324773150720    693.989990
20   BABA   322802089984    135.210007
47     GE   316117188608    299.690002
24   CSCO   309489238016     78.330002
37    UNH   256046268416    282.089996
32    MCD   232963293184    326.459991
34    WFC   232606154752     74.099998
39    IBM   231111393280    246.279999
21   INTC   228629315584     45.770000
27    PEP   218610352128    159.880005
15     VZ   216704614400     51.380001
41   AMGN   197411962880    366.209991
36      T   196519526400     27.719999
35      C   184885526528    105.690002
29    CRM   180681719808    192.830002
43   GILD   179993575424    144.990005
12    DIS   176079601664     99.290001
46     BA   164940824576    209.889999
25    PFE   151140990976     26.580000
42   SBUX   112961593344     99.150002
40    MDT   111877734400     87.139999
22  CMCSA   109899857920     30.160000
16   ADBE   102345859072    249.320007
33    NKE    79911092224     53.980000
48    MMM    79510634496    150.960007
28   ABNB    75718615040    126.300003
45     GM    67529830400     72.389999
44      F    46557175808     11.670000
19   PYPL    42010775552     44.900002
17    NIO    14817943552      5.860000

## Taking Top 10 Stocks as per the market cap

In [49]:
df = df.head(10)
df.reset_index(inplace = True, drop = True)
df

  Ticker     Market Cap  Latest Price  Number of Shares to buy
0   NVDA  4380976218112    180.250000                       11
1   AAPL  3676245065728    250.119995                        7
2  GOOGL  3656681259008    302.279999                        6
3   MSFT  2939877064704    395.549988                        5
4   AMZN  2229321072640    207.669998                        9
5    TSM  1754646446080    338.309998                        5
6   TSLA  1467951349760    391.200012                        5
7    WMT  1008725131264    126.519997                       15
8    JPM   764446900224    283.440002                        7
9    XOM   650515120128    156.119995                       12

In [50]:
portfolio_size = int(input("Enter the amount you want to invest: "))
position_size = portfolio_size / len(df.index)
position_size

10000.0

In [51]:
df['Number of Shares to buy'] = df['Latest Price'].apply(lambda price: math.floor(
    position_size / price
))
df

  Ticker     Market Cap  Latest Price  Number of Shares to buy
0   NVDA  4380976218112    180.250000                       55
1   AAPL  3676245065728    250.119995                       39
2  GOOGL  3656681259008    302.279999                       33
3   MSFT  2939877064704    395.549988                       25
4   AMZN  2229321072640    207.669998                       48
5    TSM  1754646446080    338.309998                       29
6   TSLA  1467951349760    391.200012                       25
7    WMT  1008725131264    126.519997                       79
8    JPM   764446900224    283.440002                       35
9    XOM   650515120128    156.119995                       64